version: '3.9'
services:
  bootstrap:
    image: registry1.dso.mil/ironbank/f5-networks/nginx-plus-software-adc:1.24.2
    init: true
    restart: always
    hostname: bootstrap
    volumes:
        - ./scripts:/tmp/app
        - ./ca:/tmp/ca
    extra_hosts:
        - 'bootstrap:172.20.0.2'
        - 'nginx:172.20.0.3'
    command: 'bash -xe /tmp/app/bootstrap.sh'
    networks:
      dockernet:
        ipv4_address: 172.20.0.2
  nginx:
    image: registry1.dso.mil/ironbank/f5-networks/nginx-plus-software-adc:1.24.2
    hostname: nginx
    depends_on:
      - bootstrap
    volumes:
        - ./scripts:/tmp/app
        - ./ca:/tmp/ca
        - ./nginx-conf.d:/etc/nginx/conf.d
    networks:
      dockernet:
        ipv4_address: 172.20.0.3
    ports:
        - 8443:8443
networks:
 dockernet:
  driver: bridge
  ipam:
   config:
   - subnet: 172.20.0.0/16
